//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PrepTime { get; set; }
        public int Serves { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public int MealTypeID { get; set; }
        public int StepID { get; set; }
        public Nullable<bool> IsFav { get; set; }
    
        public virtual MealType MealType { get; set; }
        public virtual Step Step { get; set; }
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
